### ISSUE TITLE
Could not find any runner configurations in nx.json

### ISSUE THREAD

**Issue by LenaLenina** [PacktPublishing/Angular-Cookbook-2E#30]
I don't know if it's a problem for me or if it's a global issue. After running npm install, everything seems fine. Each npm package is installed in both the 'start' and 'final' projects. However, when I tried the command 'npm run serve cc-inputs-outputs both', I encountered the error "Could not find any runner configurations in nx.json".

Here's what helped me:

Open the 'start' folder.
Delete the 'node-modules' folder and the 'package-lock.json' file.
Run npm install for the 'Start' project.
Repeat these steps for the 'Final' project.

**Comment by AhsanAyaz** [comment]
Thanks for reporting @LenaLenina !
I'll have a look!

**Comment by AhsanAyaz** [comment]
@LenaLenina I couldn't reproduce the issue.
Could you share the following details?
- Operating system
- Node version
- Nx version (installed)
